Natural Text
I have a dict subclass like this:This class can be used with eval and exec without issues:But if I instantiate a function object with the types.FunctionType constructor, the function can't access any builtins:Replacing MyDict() with globals() or dict(globals()) or event {'__builtins__': __builtins__} makes the code print <class 'bytearray'> as expected.I don't understand where this exception is coming from. Can anyone explain this behavior? Why does it work with eval but not with a function object?
Not a complete answer, but what seems to be happening is that CPython ignores the custom __getitem__ when it accesses the builtins. It seems to treat MyDict like a normal (not subclassed) dict. If the '__builtins__' key is actually present in the dict, then everything works correctly:The question remains why this only happens with FunctionType, and not with eval and exec.


Answer URL
https://docs.python.org/3/library/functions.html#eval
https://docs.python.org/3/library/functions.html#exec
https://docs.python.org/3/library/types.html#types.FunctionType
