Natural Text
as I am trying to print financial data:I get the error that df does not exist, or more specifically:I have no clue how to fix this, as this code seems to be working with everyone else who is trying it. I am just a beginner, so any help would be really appreciated.Thank you!Greetings, Tristan
It is known bug in shutil library:https://bugs.python.org/issue24920https://bugs.python.org/issue24966It seems, you should change the way you started you code (from GUI or from shell and similar)
This is not a full solution, but at least a workaround.You can use shutil's get_terminal_size() instead. There's also a backport available for python 2.
I faced the same problem with the code below:An easy hack would be to shift your work to the Python shell, instead of IDLE (in my case, working on IDLE was the problem, but this same code ran perfectly on the Python Shell)


Answer URL
https://docs.python.org/3/library/shutil.html#shutil.get_terminal_size
