Natural Text
How to know if an exception has occured in a Parent class method while overriding the same method in the child class ?
Your PrivCustomer.withdraw method will replace the Customer.withdraw method for PrivCustomer objects.  To call Customer.withdraw, you have to use super().withdraw to get the inherited method.  That method call will be where LimitException is raised


Answer URL
https://docs.python.org/3/tutorial/errors.html#handling-exceptions
